# Generated by Django 3.0.6 on 2020-05-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0010_auto_20200522_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutestd',
            name='afd',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institutestd',
            name='application',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institutestd',
            name='bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institutestd',
            name='ch_no',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='institutestd',
            name='dop',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institutestd',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institutestd',
            name='recipt',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institutestd',
            name='undertake',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
